language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: RxXmd/a4HYSZJxqw/ly+4RohBiun9iSGdlEIWuXOqfKTCy68htuzjkzmNo5bKocpY+SQx1TawoXpm9K4m+lRow3WeB5j3gFZpCi291bGGlMGYlYor1q/15gbo0hyjJlal7X9HEOP/JQ3WPGNzKc15EHEAZWsPYJwFPU9HeKfUM83rwiPNt7MdqA5ecqlTx1V1cdyGgaF8TygoVTEGu/9f5pw7ITNk1lxpdiO7aznUZ4Kpljtx3+tCrB2wgqTdUGB05BLVDaZs1T7kNzdmRaRndNajeZoi9n3Tu9TV4eiUCCzewfmwPOYOGBpv8ozovLIiSSNUZlBq6sRn0pwpwsddtLtDRReWGGtSfI/0ByqQTmtSE5TD0ihMV/aaShb3NZSd71n/Klav2o4iwlVpGHkSHzvWWleiSbTfbT6HKHLJiGIcJp5DyWHXyhOOrbdB2FRY7NN5Dp2OrZZLn+OV656ZBkt1MK/9TohjD8pnoWAqU0h3B1ia2rvjNlSHdiQTjk+gvlNPNCLCIQuBPApVPvn1gXoulbRsGTFq4VD2maDrbzyquzvX6Cjv+IBqedzBaFHUwjklsfNOGddiR/douhQliOlXbCgA6c1gWRvNIGnH/LPBXbrGm6PE0CSxHnbT2nvf/W1ik7BQreq2MUKISfuzhqacg8o1sB9g5hAEaLAuQs=
  app: projetlp
  on:
    repo: EdemosBonboy/projet
