language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: "PSwln5FfGrkMx5Off6eAgLBfmCDSbkawoKR8IXeA8ChKc1MAu1mlHfb52VuqNuMwGo3KOOfqIfSJdFaw7np5WZEBkfEflO3fIHAzVPKe0NUpoQ2M2wc4+/0Bk/I73WYNKyNCCmO2r4HQBAYcm+i1nu6k5DdzYB2EoUbrQy9Iar2hjYlRPLDMxl6R/M5gUahzh6JrIPpmqieIQfSHvtdtBsJUVK9R6SE2orWiuuYIMrYBu+h3NCDLf/hfDx4m1Itfca6EB5Wp0C04d6bTrcEHnV+GzS1u4gv3NSoXiUXE9xUd1J5HUq3JPEU+z7bUkMYpRkRNUfMxDlWserJWC+M+oG+zdv7Ss4EpBs5lddj0dyC3NQCgI7WRgWpN15ifWBG55K85rAFC0+bCg8DmbtRGdFREjFubWHWjVms1qdBprTBvpUriDsDl/gHI/chrw/H1ux2aoWB2o9QdbGMZetjl8+cWXLFTK49BTFKoV59szOs1HZLt2MgQpW27ikeypxGiJDrn08TH8gL29pGaotBN8SV66sMhJb44QyDDPPXJokHynGuJfVDXhp7uQ1sC0TipX+XwmHDaAbp0bDJsgtmgPbsHEdJuJbDESF/8F5YcK8Fh3SaO5EXbQlO48CbnZN03to1Og70C2ygo0NDQ4nMiM65Q5pdjOLqFY4n2TFJbbIU="
